data_path: 'data'
batch_size: 64
num_workers: 4
max_seq_length: 128
bert_model: 'bert-base-uncased'
learning_rate: 0.0001
validation_split: 0.2
output_dir: 'output'
gpus: 1
train_only_head: False
min_epochs: 10
max_epochs: 100
patience: 3