data_path: 'data'
batch_size: 512
num_workers: 4
max_seq_length: 128
bert_model: 'bert-base-uncased'
learning_rate: 0.001
validation_split: 0.2
output_dir: 'output_aug'
gpus: 1
train_only_head: True
min_epochs: 100
max_epochs: 200
patience: 5
augment: True